# Generated by Django 3.2.9 on 2021-11-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account_no',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.IntegerField(max_length=10),
        ),
    ]
