# Generated by Django 3.1 on 2022-04-06 03:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account_no',
            field=models.PositiveIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.PositiveIntegerField(max_length=6),
        ),
    ]
